### ISSUE TITLE
How to compile w5500 driver for android.

### ISSUE THREAD

**Issue by YumingMa** [Wiznet/ioLibrary_Driver#26]
Dear,

I want to poring it to android. How to compile w5500 driver for andrioid? I see w5300 code at path "kernel/drivers/net/ethernet/wiznet". Why not add  w5500 code into kernel driver?.
Thanks.

**Comment by renakim** [comment]
Unfortunately, the android kernel does not include the W5500 driver.

If you want to use the W5500, you have to add the driver code to the kernel.
Please refer to the below link.
* [https://github.com/borg42/w5x00](https://github.com/borg42/w5x00)

Thank you.

**Comment by renakim** [comment]
Hi,
The w5500 driver has been added since the official Linux kernel 4.7 or later.

If the Android kernel version is 4.7 or higher, it may be supported. 
Please check this and refer to the below link.

* [Linux kernel commit history: support W5500](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=35ef7d689d7d54ab345b179e50c749fe3a2529eb)

Thank you.
